### PR TITLE
more tests

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by jakirkham** [comment]
FYI @bgruening as this was pushed to a branch on the feedstock this has already deployed a package. Would recommend closing it out and making a new PR from a branch on your fork of the feedstock. Will need an additional build number bump to get a fresh package built.

**Comment by bgruening** [comment]
Even if the branch was never build successfully? Didn't know that. Sorry.

**Comment by bgruening** [comment]
Mh, I don't see it in the channel.

**Comment by jakirkham** [comment]
Good point, if it was always failing, it wouldn't have deployed.

**Pull request closed without merging**
